Update release notes generation
kubernetes-sigs/kustomize pull request #3252
Opened 2020-11-19 23:32 UTC by runewake2

Fixes #2773

Update to release notes generation to use the current tag and the tag prior to it instead of using a commitSha.

The previous tag version is detected using tag version numbers.

2020-11-19 23:34 UTC, Shell32-Natsu requested changes

2020-11-19 23:34 UTC, Shell32-Natsu commented on releasing/cloudbuild.sh
> +prevTag=$(git tag -l "$module*" --sort=-version:refname --no-contains=$currentTag | head -n 1)
`currentTag` should be `fullTag`

2020-11-19 23:39 UTC, Shell32-Natsu commented
/ok-to-test
/lgtm

2020-11-20 18:14 UTC, monopole commented
eager to try this
/lgtm

2020-11-20 18:24 UTC, merged