docs: Add documentation for namespace transformer
kubernetes-sigs/kustomize pull request #4906
Opened 2022-12-05 00:06 UTC by larsks

Add a short description of the namespace transformer and example
usage to examples/transformerconfigs/README.md.

Closes: #629
Signed-off-by: Lars Kellogg-Stedman <lars@oddbit.com>

2022-12-06 23:51 UTC, natasha41575 commented
/cc @koba1t

2022-12-08 12:34 UTC, koba1t requested changes
@larsks 
Thanks for your contribution!
I've added a few comments about the appearance of this doc.
Please check there!

2022-12-08 12:34 UTC, koba1t commented on examples/transformerconfigs/README.md
> +  - namespace.yaml
Please remove spaces from the extra indent on this list.
I think our style is no extra indent for lists.

2022-12-08 12:34 UTC, koba1t commented on examples/transformerconfigs/README.md
> +    create: true
Please remove spaces for the same reason.

2022-12-08 12:34 UTC, koba1t commented on examples/transformerconfigs/README.md
> +namespace: example
I think if we add a new line before `namespace: example`, this example is easy to understand.

2022-12-08 14:07 UTC, larsks commented
@koba1t thanks for the review! I think I've addressed all your requests.

2022-12-09 14:57 UTC, koba1t commented
@larsks
Thanks for your fix!

/lgtm

2022-12-09 17:12 UTC, natasha41575 reviewed
Ideally each transformer doc would be in its own separate folder,  (like how `images` and `crds` have their own folders). That doesn't have to be in this PR, but would be a welcome change in a followup if you have the time.

2022-12-09 17:12 UTC, natasha41575 commented on examples/transformerconfigs/README.md
> +## Namespace
nit: move this section to right below the AnnotationsTransformer, so that the simpler transformers are all together.

2022-12-09 21:13 UTC, natasha41575 commented
/lgtm
/approve

2022-12-09 21:27 UTC, merged