kustomize: Add support for OCI based helm repos
kubernetes-sigs/kustomize pull request #5167
Opened 2023-05-10 07:19 UTC by jkroepke

Bitnami recently change from classical helm repositories to OCI based repositories, which may have an impact of the support for helm charts from OCI repositories.

this PR add support for fetch charts from OCI repositories.

Example:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: external-dns
#  repo: https://charts.bitnami.com/bitnami
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 6.19.2
  releaseName: external-dns
  namespace: external-dns
  valuesFile: values.yaml
```

This PR does not implement a breaking change.

Fixes #4614

2023-05-17 00:15 UTC, jkroepke commented on api/internal/builtins/HelmChartInflationGenerator.go
> +			args = append(args, "--repo", p.Repo)
You are right.

```suggestion
			args = append(args, "--repo", p.Repo, p.Name) 
```

2023-05-17 00:16 UTC, jkroepke commented on plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
> +			args = append(args, "--repo", p.Repo)
```suggestion
			args = append(args, "--repo", p.Repo, p.Name) 
```

2023-05-17 00:18 UTC, jkroepke commented
/label tide/merge-method-squash

2023-05-17 00:33 UTC, soudaburger approved these changes

2023-05-24 17:27 UTC, natasha41575 commented
/ok-to-test

2023-05-24 18:52 UTC, koba1t commented
Hi @jkroepke
Thanks for your contribution!

This PR almost looks good to me.
So, it looks like the lint failed on CI. Could you check it and fix it?

2023-05-26 13:41 UTC, DanielYWoo commented
Do we have an ETA for this to be released?

2023-05-26 16:05 UTC, koba1t commented
@jkroepke 

I found the below error when running on my laptop. Could you fix it?

```
api/krusty/helmchartinflationgenerator_test.go:49:7: var-naming: const expectedHelmExternalDns should be expectedHelmExternalDNS (revive)
const expectedHelmExternalDns = `
      ^
make[1]: *** [lint] Error 1
make: *** [lint] Error 2
```

2023-05-26 16:23 UTC, jkroepke commented
Done

2023-05-26 16:30 UTC, koba1t commented
@jkroepke

Thanks!
Almost looks good to me!
/lgtm

@natasha41575 
Could you check this PR and rerun GitHub Actions?

2023-05-26 16:31 UTC, koba1t commented
/cc @natasha41575 
Could you check this PR and rerun GitHub Actions?

2023-06-13 14:23 UTC, robertsa1-els commented
Any movement on this.  It is not long till Bitnami are due to drop support and GitHub Scalesets is OCI only.
Thanks in advance 👍

2023-06-13 14:26 UTC, koba1t commented
/lgtm

2023-06-20 07:06 UTC, jkroepke commented
@koba1t how to proceed here? I'm bored of constantly rebase this PR.

2023-06-20 09:13 UTC, koba1t commented
@jkroepke 
We need to wait for the review of the maintainers.

/cc @natasha41575 @annasong20

2023-06-20 10:46 UTC, jkroepke commented
@koba1t because of the rebase, the lgtm flag has been removed

2023-06-20 11:51 UTC, koba1t commented
Thanks
/lgtm

2023-06-20 15:13 UTC, jkroepke commented
@koba1t are you able to trigger to CI here? Just to confirm that everything is green.

2023-06-20 15:15 UTC, koba1t commented
@jkroepke
> @koba1t are you able to trigger to CI here?

Sorry... I don't have that permission. Only the maintainer can do that operation...

2023-06-23 07:13 UTC, jkroepke commented
Alright, I hope that  @natasha41575 @annasong20 will find some time, soon.

2023-07-04 10:05 UTC, tolgaio commented
just pinging @natasha41575 @annasong20 again, we've been waiting for this for a long time now as well, it feels we are nearly there, could you please trigger the CI and help us here to get this merged. thanks a bunch!

2023-07-06 23:21 UTC, FrenchBen approved these changes
LGTM

2023-07-06 23:24 UTC, jkroepke commented
/assign knverey

2023-07-17 08:34 UTC, diegoluisi commented
@natasha41575

2023-07-17 21:15 UTC, annasong20 commented
/assign

2023-07-20 19:35 UTC, diegoluisi commented
Hope that @annasong20, @yuwenma or @natasha41575 approve this PR soon..

2023-07-26 23:46 UTC, shakefu commented
3 months into merging a 140 line PR? Is this dead in the water?

2023-08-04 17:28 UTC, jkroepke commented
@natasha41575 do you have any idea to proceed here? @KnVerey seems unresponsive and I see a lot of recent contribution from you on main.

/assign @natasha41575

2023-08-10 17:28 UTC, spstarr commented
Really needing this feature with Config Sync

2023-08-15 08:47 UTC, cheelim1 approved these changes
LGTM

2023-08-16 14:42 UTC, natasha41575 commented
/test all

2023-08-16 14:43 UTC, natasha41575 commented
I am not sure why the tests aren't running, the button to run them isn't there. Could you try pushing something to see if it runs the tests?

2023-08-16 19:19 UTC, jkroepke commented
@natasha41575  now it says "workflows awaiting approval"

2023-08-21 16:24 UTC, hawkesn commented
The tests look like they passed? I think it just needs the lgtm labels?
![image](https://github.com/kubernetes-sigs/kustomize/assets/1168175/d21c3dc7-2098-4ec8-90a0-87c6f1f10c2b)

2023-08-21 20:45 UTC, soudaburger commented
LGTM

2023-08-22 17:15 UTC, soudaburger commented
Can we get the LGTM and any other necessary labels on this.  We're so close finally!

2023-08-23 01:07 UTC, bruceoutdoors commented
LGTM

2023-08-23 06:51 UTC, stesme commented
Can someone put an LGTM on this PR, please 🙏

2023-08-29 13:01 UTC, bruceoutdoors approved these changes

2023-08-29 18:12 UTC, joshuabaird commented
@annasong20 Is there anything we can do to help move this forward and get it merged?

2023-08-29 18:14 UTC, tolgaio commented
🍿

2023-09-04 11:35 UTC, NigelVanHattum commented
@natasha41575 Could you take a look at the PR again. All tests are green, we only need the LGTM tag.

2023-09-14 08:02 UTC, pkruk commented
ping?

2023-09-14 08:50 UTC, koba1t commented
/lgtm

2023-09-15 12:14 UTC, ramizpolic commented
Any info on when we can expect this PR to be merged?

2023-09-18 17:34 UTC, annasong20 requested changes
@jkroepke I think this PR mostly looks good! My concerns are relatively minor. Would value @natasha41575's feedback, as she has more Helm expertise, but otherwise I can give my approval after the requested changes are fixed.

I sincerely apologize for the huge delay in my review. It's a continual combination of limited bandwidth and a long backlog.

2023-09-23 07:22 UTC, jkroepke commented on plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
> +			args = append(args, fmt.Sprintf("%s/%s", strings.TrimRight(p.Repo, "/"), p.Name))
At least, there is one https://github.com/kubernetes-sigs/kustomize/pull/5167/files#diff-28bb15d994f41f933c7d9304d77227b0805245111b7590b293456733b8758292R188 or I'm wrong?

2023-09-23 07:35 UTC, jkroepke commented
@annasong20 Thanks for your review, I applied all your suggestion. They make sense my eyes.

2023-09-27 15:47 UTC, jmrr commented
Thank goodness I found this and the #4381 issue, I was already going to beat my head against the wall, as the [charts](https://github.com/actions/actions-runner-controller/tree/master/charts) we're using are only published in an OCI repo. Subscribed to the PR and looking forward to seeing it released. Thank you!

2023-09-30 19:14 UTC, koba1t commented
/assign koba1t
/unassign @annasong20 @natasha41575 @KnVerey

2023-10-04 15:56 UTC, koba1t commented on plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
> +			args = append(args, fmt.Sprintf("%s/%s", strings.TrimRight(p.Repo, "/"), p.Name))
I think @annasong20 wants to add two type tests one of an OCI repo doesn't end with a "/" and the OCI repo ends with a "/" word.
Could you add another type of test?

2023-10-04 15:56 UTC, koba1t commented
Hi @jkroepke

I'll review this PR instead of @annasong20 because she is still busy.
I was promoted to `approver` last month, and that means I can `approve` this PR.

Looks like almost good for your PR.
I have two nit comments. Could you check these?
I'll merge this PR after these are fixed.

2023-10-04 15:58 UTC, koba1t commented on go.work.sum
Could you execute the `go work sync` command?
I found the diff after exec this command in my laptop.

2023-10-04 18:28 UTC, jkroepke commented on go.work.sum
I run `go work sync` which introduces a lot of changes in a go.mod/go.sum files.

In case, that not intended, please commit to this PR directly, since "Allow edits and access to secrets by maintainers" is enable and I can not validate whats is correct here.

2023-10-04 18:41 UTC, koba1t commented on go.work.sum
> In case, that not intended,

No, You completed what I wanted!

2023-10-04 18:42 UTC, koba1t commented on plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go
> +			args = append(args, fmt.Sprintf("%s/%s", strings.TrimRight(p.Repo, "/"), p.Name))
@jkroepke 
Could you check it?

2023-10-05 03:43 UTC, DanielYWoo commented
appreciate your work but I think the change process to k8s is an overkill.

2023-10-11 07:38 UTC, NigelVanHattum commented
@koba1t Can we get this merged? :-)

2023-10-11 09:44 UTC, jkroepke commented
did get the notify for that, I will take not of it!

2023-10-15 09:30 UTC, jkroepke commented
@koba1t I added a test and do a merge from master

2023-10-17 19:15 UTC, koba1t commented
@jkroepke

Thank you for adding another test and for your continued attention to this PR over an extended period. 
This PR looks good to me. I'll merge this PR!

/approve

2023-10-17 19:19 UTC, koba1t commented
/lgtm

2023-10-17 19:24 UTC, merged

2023-10-18 11:43 UTC, aristosvo commented
Thanks @koba1t and @jkroepke!

Can we expect a release with this functionality in the near future?

2023-10-19 21:34 UTC, natasha41575 commented
This is available in the latest release.

2023-10-21 13:34 UTC, MPV commented
Beautiful!

Looking to add it into ArgoCD over at:
- https://github.com/argoproj/argo-cd/pull/16054#issuecomment-1772815169

2024-01-15 04:48 UTC, zimmertr commented
Is this not working with GHCR? The [repo](ghcr.io/sergelogvinov/charts/proxmox-csi-plugin) is public?

```yaml
helmCharts:
  - name: csi-proxmox
    repo: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    version: 0.1.15 # https://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    releaseName: csi-proxmox
    namespace: csi-proxmox
```

> Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%!A(MISSING)sergelogvinov%!F(MISSING)cha
rts%!F(MISSING)proxmox-csi-plugin%!F(MISSING)csi-proxmox%!A(MISSING)pull&service=ghcr.io: 403 Forbidden

2024-01-15 06:33 UTC, koba1t commented
@zimmertr 

We don't plan to support `private repository or registry authentication` in `helmCharts`.
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/#the-current-builtin

2024-01-15 06:54 UTC, koba1t commented
@zimmertr

I think you made a mistake in your `kustomization.yaml` file; the below file works on my computer.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: proxmox-csi-plugin
    repo: oci://ghcr.io/sergelogvinov/charts
    version: 0.1.15 # https://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    releaseName: csi-proxmox
    namespace: csi-proxmox
```

https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_

2024-01-15 07:54 UTC, zimmertr commented
Doi, Thank you :)

2024-01-18 07:34 UTC, marcusnh commented
Hello, I have the same problem with [my setup](https://github.com/argoproj/argo-cd/issues/16894) to Azure Container Registery:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Referencing a public repo outside the main repository

helmCharts:
  - name: <ARO-REPO-CHART-NAME>
    repo: oci://ACR-NAME.azurecr.io/
    version: 0.1.6-5
    releaseName:ARO-REPO-NAME
    namespace: poseidon2-dev
    valuesFile: values.yaml
```
The error message is also similar:
```
level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): `kustomize build <path to cached source>/applicationsets/dev/demo-helm-2 --enable-helm` failed exit status 1: Error: Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://<ACR-NAME>.azurecr.io/oauth2/token?scope=repository%!A(MISSING)<ARO-REPO-NAME>%!F(MISSING)<ARO-REPO-NAME>%!A(MISSING)pull&service=<ACR-NAME>.azurecr.io: 401 Unauthorized\n: unable to run: 'helm pull --untar --untardir <path to cached source>/applicationsets/dev/demo-helm-2/charts oci://<ACR-NAME>.azurecr.io/<ARO-REPO-NAME>/<ARO-REPO-NAME> --version 0.1.6-5' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-3509023410/helm HELM_CACHE_HOME=/tmp/kustomize-helm-3509023410/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-3509023410/helm/.data] (is 'helm' installed?): exit status 1" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-01-17T09:44:38Z" grpc.time_ms=2.234 span.kind=server system=grpc
```

2024-01-18 07:50 UTC, koba1t commented
According to your error message, you failed to exec `helm pull` command.
Please try to exec `helm pull` directly to check if the helm chart is valid.

2024-01-18 08:00 UTC, marcusnh commented
This works fine on my local computer. I'm able to run helm pull:
```
helm pull oci://ACR-NAME.azurecr.io/ARO-REPO-CHART-NAME  --version 0.1.6-5
Pulled: ACR-NAME.azurecr.io/ARO-REPO-CHART-NAME:0.1.6-5
Digest: sha256:9be2d3dd16cee312918f2b321453683e8b-NOT-THE-SAME-57b
```
I have also tested the chart with a ArgoCD application and that works fine with the kubernetes secret passed to my ArgocD instance:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-<ARO-REPO-NAME>
  namespace: gitops-developers # argocd instance namespace
spec:
  source:
    chart: <ARO-REPO-CHART-NAME>
    repoURL: <ARO-NAME>.azurecr.io
    targetRevision: 0.1.6-5
    helm:
      values: |
        application_name: "<ARO-REPO--CHART-NAME>-test"
        namespace: poseidon2-test

  destination:
    namespace: poseidon2-test
    server: https://kubernetes.default.svc
  project: poseidon2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    # syncOptions:
    #   - Replace=true
```

2024-01-18 08:22 UTC, koba1t commented
> I have also tested the chart with a ArgoCD application and that works fine with the kubernetes secret passed to my ArgocD instance:

I apologize for not knowing the details of ArgoCD. Do you use any credentials to pull helm charts?
kustomize doesn't support private repository or registry authentication for helm pull.
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/

2024-01-18 08:49 UTC, TeamPoseidonOCP commented
To get access to the private ACR, I need some form of authentication, and creating helm credentials with a Kubernetes secret has been sufficient to get access with ARgoCD. 

In the link you sent, it says: "We will not add support for:
* private repository or registry authentication
* OCI registries
* other large features that increase the complexity of the feature and/or have significant security implications."

OCI registries are now supported. Are there no planned features for enabling private repositories or registry authentication? This would help us a lot and simplify the setup for our developers.

2024-01-18 09:48 UTC, koba1t commented
Sorry, we don't have a plan to add more functions to helmCharts now.

2024-01-18 10:13 UTC, MrFreezeex commented
> To get access to the private ACR, I need some form of authentication, and creating helm credentials with a Kubernetes secret has been sufficient to get access with ARgoCD.

FYI I put some observation possible followup on this (private oci support): https://github.com/kubernetes-sigs/kustomize/issues/5407#issuecomment-1804441770 and there is two possible (ugly) workaround that you could do with existing versions

2024-01-18 10:18 UTC, felixlut commented
I think the above issues are related to this ticket: https://github.com/kubernetes-sigs/kustomize/issues/5407

My workaround for the time being is to run kustomize build in CI (with a short bash script as a workaround to auth to my private helm registry), generate a manifest.lock.yaml containing the entire k8s manifest, and have Argo cd look at that directly. Essentially move the kustomize build step from ArgoCD to CI instead, since I have more control there.

This is also consistent with the rendered manifests pattern:
https://akuity.io/blog/the-rendered-manifests-pattern

With all that said, I really think that kustomize should respect the local Helm credentials, as mentioned in the issue I linked above

2024-01-18 11:52 UTC, marcusnh commented
Thank you for the feedback. I saw the workarounds, and there is the possibility to add them with a config map to the ArgoCD instance, but I think we will have to use another approach until this is supported. Using the workaround provided in the ticket [#5407](https://github.com/kubernetes-sigs/kustomize/issues/5407) will fix the problem, but it is not the cloud-native way that we prefer to do things. I think we will have to stick with ArgoCD applications and helm integration until this is supported.  
Is there a feature request that I can follow or contribute to?

2024-01-18 15:26 UTC, jkroepke commented
About the authentication issues, you can use helm login, crane login or docker login before running kustomize. The helm OCI integration will re-use the docker credentials for authentication. If you are running private ACR with Azure RBAC, consider to use `az acr login` instead `docker login`.

2024-01-18 16:54 UTC, jkroepke commented
Tested with ghcr.io. Works fine.

2024-01-18 17:08 UTC, MrFreezeex commented
Actually it does seems to work with helm 3.13.3 indeed thanks! Pretty sure there is something that affected the usage of helm through kustomize that got fixed at the helm level in the last couple of months as I was not alone affected by this so it would be weird that we all messed up at the same time 🤔. Anyway looks fixed to me!

2024-01-19 08:55 UTC, marcusnh commented
Is there an update from v3.13.2 to v3.13.3 that has fixed the authentication issues?
Our infrastructure is using ArgoCD to provision applications for our developers, so we need a way of doing the `helm registry login` command through that API.  Similar to ArgoCD already does today through ArgoCD applications.
>  If you are running private ACR with Azure RBAC, consider to use az acr login instead docker login.
Need to be able to use any registry,  not just ARC.

2024-01-21 09:09 UTC, marcusnh commented
It is kustomize that doesn't support private OCI registries, so the issue needs to be fixed there and not in ArgoCD. This feature request is only to make kustomize more compatible with ArgoCD and Helm. It is possible to add a workaround, but it is not very cloud-native. Take a look at this issue; might clear up why this is a kustomize problem and not an ArgoCD error:
- https://github.com/argoproj/argo-cd/issues/16623

2024-01-21 09:36 UTC, jkroepke commented
It does support it. See above.

ArgoCD is should provide the authenticated context. Argo does this for helm, too.

You can also run helm registry login before running kustomize.