[refactor]: Internalize loader api
kubernetes-sigs/kustomize pull request #5193
Opened 2023-06-07 15:03 UTC by varshaprasad96

This PR intends to move the loader api to
internal. Only the necessary methods which
are needed for the api have been put into
`pkg/loader.go`.

2023-06-07 15:22 UTC, natasha41575 commented
Thanks for the PR @varshaprasad96! @koba1t could you give this a review? The related issue is https://github.com/kubernetes-sigs/kustomize/issues/3942

/assign @koba1t

2023-06-07 18:27 UTC, koba1t requested changes
@varshaprasad96 
I've commented on a minor change.
Could you check it?

2023-06-13 18:38 UTC, varshaprasad96 commented
@natasha41575 @annasong20 Could we merge this? Thanks!

2023-07-12 18:04 UTC, annasong20 commented
/assign

2023-09-13 17:16 UTC, natasha41575 commented
@varshaprasad96 some tests are failing, could you address those?

2023-09-27 21:38 UTC, natasha41575 commented on api/pkg/loader/loader.go
> +// Copyright 2019 The Kubernetes Authors.
nit: 2023

2023-09-27 21:39 UTC, natasha41575 reviewed
/lgtm
/approve

/hold

Feel free to remove the hold when you update my nit above and ping me for another lgtm.

2023-09-28 14:50 UTC, varshaprasad96 commented on api/pkg/loader/loader.go
> +// Copyright 2019 The Kubernetes Authors.
Addressed

2023-09-28 14:51 UTC, varshaprasad96 commented
/remove hold

2023-09-28 15:36 UTC, merged