Documentation for contributor guide #5199
kubernetes-sigs/kustomize pull request #5209
Opened 2023-06-16 07:34 UTC by Shekharcodess

I have updated the documentation for the contributors guide and I have made sure all the mentioned points are covered

2023-06-28 18:18 UTC, koba1t commented
/assign

2023-07-01 19:06 UTC, koba1t requested changes
Hi @Shekharcodess

Thanks for your first contribution!
The code base of `kustomize` is just a bit complicated and doesn't use typical commands on `Makefile`.
Could you check for `Makefile` on the repo root and try that make commands on your computer?

And I recommend checking the below two files for what is running on CI.
- https://github.com/kubernetes-sigs/kustomize/blob/da4e8810079e2a98a3f4caad83618c53014d703b/.github/workflows/go.yml
- https://github.com/kubernetes/test-infra/blob/da4337756e8bba3a39a5cfb21997b2d35d1171f2/config/jobs/kubernetes-sigs/kustomize/kustomize-presubmit-master.yaml

2023-08-19 01:53 UTC, annasong20 commented
Hi @Shekharcodess, are you still working on this PR? We plan to increase its priority, so if you aren't someone else might assign #5199 to themselves.

2023-08-30 14:44 UTC, varshaprasad96 commented on CONTRIBUTING.md
> +Ensure that you have Go installed on your system. Refer to the [Go](https://golang.org/doc/install) installation guide for your platform.
It would be nice to specify that we recommend to use the version supported in go mod.

2023-08-30 14:44 UTC, varshaprasad96 commented on CONTRIBUTING.md
> +Optionally, you can add the bin directory to your system's PATH environment variable to use the locally built Kustomize binary.
```suggestion
Optionally, you can add the bin directory to your system's $PATH environment variable to use the locally built Kustomize binary.  
```

2023-08-30 14:44 UTC, varshaprasad96 commented on CONTRIBUTING.md
> +Overview of Important Make Targets and Running Tests Locally:
Nit:
```suggestion
Overview of important `Make` targets and running tests locally:
```

2023-08-30 14:44 UTC, varshaprasad96 commented on CONTRIBUTING.md
> +`make test`: Run the tests for Kustomize locally.
Neither is there `test-e2e` `coverage`

2023-09-29 17:45 UTC, natasha41575 commented
Closing due to lack of activity

2023-09-29 17:45 UTC, closed without merging